### ISSUE TITLE
Improve Employee Page Update UX and Refactor Theme Handling

### ISSUE THREAD

**Issue by eNKay2408** [eNKay2408/POS-System#4]
- **Enhancement:** Updated the Update functionality of the Employee page to use text inputs pre-filled with the current content instead of placeholders. This ensures users don't unintentionally lose data (e.g., email) when editing specific fields like Name.
- **Refactor:** Replaced localSettings with the new SettingsService class (available in the Main branch) for managing Theme changes, ensuring a more consistent and maintainable implementation.

**Comment by CatHuyuH24** [comment]
Okay, working on it...

**Comment by CatHuyuH24** [comment]
Thanks for your suggestion, I've made a PR on update-ux-handling to improve this.

**Comment by eNKay2408** [comment]
Thanks for accepting and fixing this Issue. Your improvement will make the UX better
